language: bash

env:
  - BUILDX_VERSION=0.5.1 DOCKER_VERSION=20.10.7

services:
  - docker

branches:
  only:
    - master

script:
  - docker build --build-arg BUILDX_VERSION=$BUILDX_VERSION --build-arg DOCKER_VERSION=$DOCKER_VERSION -t kirtanpt/docker-gitlab-buildx:$DOCKER_VERSION-$BUILDX_VERSION .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kirtanpt/docker-gitlab-buildx:$DOCKER_VERSION-$BUILDX_VERSION
